version: '3'

services:
  database:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db

  backend:
    container_name: backend
    image: node-docker
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://db:27017/event-form
    restart: on-failure
    depends_on:
      - database

  frontend:
    container_name: frontend
    environment:
      - API_ENDPOINT=mylocal.com/api
    image: react-docker

  haproxy:
    container_name: haproxy
    image: my_haproxy
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
