version: '3'

services:
  database:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db

  backend:
    container_name: backend
    build: backend/
    image: node-docker
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://db:27017/event-form
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - database

  frontend:
    container_name: frontend
    build: frontend/
    image: react-docker
    ports:
      - 3000:80
